apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: mongo-deploy
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata: 
      name: mongo-pod
      labels:
        app: mongo
    spec:
      containers: 
        - name: mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017