#pod manifest file
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
spec: 
  containers: 
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  


template:
    metadata: 
      name: nginx-pod
      labels:
        app: nginx
  spec:
    containers: 
      - name: nginx-container
        image: nginx:latest
        ports:
          - containerPort: 80