apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx-container
          image: nginx:1.27
          ports:
            - containerPort: 80
    resources: