apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis
        resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: hostpath-vol
          mountPath: /redis-data
      volumes:
      - name: hostpath-vol
        hostPath: 
          path: /tmp/redis-data