- name: Create user accounts
  hosts: clients 
  remote_user: root
  vars:
    secret: Secure*123 

  tasks:
  - name: create test user on remote hosts
    user: 
      name: testuser3
      password: "{{ secret | password_hash('sha512') }}"
      shell: /bin/bash
      state: present