- name: Create user accounts
  hosts: clients 
  remote_user: root
  vars_files:
    - secret.yaml

  tasks:
  - name: create test user on remote hosts
    user: 
      name: testuser5
      password: "{{ secret | password_hash('sha512') }}"
      shell: /bin/bash
      state: present