apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-fs
  template:
    metadata:
      labels:
        app: nginx-fs
    spec:
      containers:
      - name: nginx-fs
        image: nginx
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: file-volume
            mountPath: /data      
      volumes:
        - name: file-volume
          persistentVolumeClaim:
            claimName: manual-file-claim