apiVersion: batch/v1
kind: CronJob 
metadata:
  name: print-hello-job
spec:
  schedule: "* * * * *"  # runs every minute, cron job calc https://crontab.guru/
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "Hello, Kubernetes!"
          restartPolicy: OnFailure