apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpuEnabled
                    operator: In 
                    values:
                      - "true"