apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-log-reader
rules: 
- apiGroups:
    - ""
  resources:
    - pods 
    - pods/log
    - deployments
  verbs: ["get","list","create","update"]