#pod manifest file
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  namespace: dev-team
spec: 
  containers: 
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  

