apiVersion: apps/v1
kind: Deployment  #Stateless
metadata:
  name: dyn-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: dyn-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dyn-pd-vol
              mountPath: /dynpdvoldata
      resources:
      volumes:
        - name: dyn-pd-vol
          persistentVolumeClaim: 
            claimName: dynamic-disk-claim 