apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-pd-sc
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: false 
reclaimPolicy: Retain 
parameters:
  type: pd-standard 
  fsType: ext4