- name: Create user accounts
  hosts: clients 
  remote_user: root 

  tasks:
  - name: create test user on remote hosts
    user: 
      name: testuser1
      password: test123
      shell: /bin/bash
      state: present