apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-01
  namespace: db-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-01
  template:
    metadata:
      labels:
        app: mongodb-01
    spec:
      containers:
      - name: mongodb-01
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
      resources:
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-01
  namespace: db-ns
spec:
  selector:
    app: mongodb-01
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017