apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: bitnami/mongodb-exporter:0.36.0
        args:
        - "--mongodb.uri=mongodb://admin:password@mongodb:27017"
        ports:
        - name: metrics
          containerPort: 9216
      resources:
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
  - name: metrics
    port: 9216
    targetPort: metrics
    protocol: TCP