- name: creating hostname var using command
  hosts: clients
  remote_user: root

  tasks:
  - name: creating hostname dynv var using command
    command: hostname
    register: hostname_var
 
  - name: print the value from the earlier var
    debug:
      msg: "{{ hostname_var.stdout }}"
  
  - name: install tree pkg only on client01
    apt:
      name: tree
      state: present
    when: hostname_var.stdout == "client01"